### ISSUE TITLE
tdarr logging output and library id

### ISSUE THREAD

**Issue by cryptolukas** [deathbybandaid/tdarr_inform#14]
Hi tdarr_inform working really well thank you.

tdarr inform always log on error. It is intended?

How can I provide tdarr inform the library id he is searching?
```
[2023-09-15 04:35:12,700] ERROR - No exact match found, searching for library ID from Reverse Recursive Directory matching

```

**Comment by Marly212** [comment]
Hey, iam currently running into the same Problem. Is the Script still working for you even with this error? And could you fix the Problem?

**Comment by deathbybandaid** [comment]
This is safe to ignore, it's not really an "error". Preferably, there would be an exact file match, but if it's a new file, tdarr_inform has to then use logic to find the closest directory match for the information given.

**Comment by Marly212** [comment]
I tried it with the new update and now I get the following error message in the sonarr logs while testing a custom script: 

```
[Warn] SonarrErrorPipeline: Invalid request Validation failed: 

-- : Script exited with code: 255
```

**Comment by deathbybandaid** [comment]
Not sure what that is. Not enough info to go off of

**Comment by Marly212** [comment]
Can you maybe make a completely new release with the latest update? So I could use that one
