### ISSUE TITLE
Could not Detect a supported *arr

### ISSUE THREAD

**Issue by johanruda** [deathbybandaid/tdarr_inform#15]
Hello!

Trying to get this to work but I'm stuck at the "Generate a config file using python3 tdarr_inform.py --setup" step.
I'm just getting this error instead.

Please help! :)

**Comment by modem7** [comment]
I'm getting the same whilst using it in Docker in Ubuntu. 

I've copied the script to an appropriate location, modified the file, but it seems that the `--setup` does not handle being called outside a containerised environment to generate the config.

**Comment by deathbybandaid** [comment]
easy workaround is create a file `config.ini`

and make it's contents:

````
[logging]
level = INFO
format = None

[main]
cache_dir = None

[tdarr]
address = CHANGETHIS
port = 8265
ssl = None
````
