### ISSUE TITLE
Native error= Access denied

### ISSUE THREAD

**Issue by modem7** [deathbybandaid/tdarr_inform#16]
When doing a "test" on Sonarr in Docker, I get the following message:

![image](https://github.com/deathbybandaid/tdarr_inform/assets/4349962/456bb8f1-fbaf-414b-be2e-88f28302a035)

And in Radarr:
![image](https://github.com/deathbybandaid/tdarr_inform/assets/4349962/48904d51-1e1d-41a3-9531-b86bbdb8b39a)

**Comment by deathbybandaid** [comment]
Your sonarr/radarr user needs permission to run it

**Comment by modem7** [comment]
> Your sonarr/radarr user needs permission to run it

Aye, I have made sure that the right UID/GID is set (for what user radarr/sonarr is running under in Docker), and have also +x'd the .py files just in case.

**Comment by deathbybandaid** [comment]
I am working on a new feature that will allow tdarr_inform to act as a web service to bridge the gap. it may be an alternative for your issue.
