### ISSUE TITLE
Rewrite the path?

### ISSUE THREAD

**Issue by sbcrumb** [deathbybandaid/tdarr_inform#22]
I use a mergerfs that has my local/cloud/NAS in the dir
/mnt/unionfs/Media/
This is the path sonarr/radarr send. but tdarr uses /mnt/local/Media(as I dont' want tdarr to run on the other drives)
Is there a way to get the inform to rewrite the dir when it informs tdarr?

**Comment by deathbybandaid** [comment]
This script doesn't have that ability (see readme.MD)
