### ISSUE TITLE
couple recommendations

### ISSUE THREAD

**Issue by D0cR3d** [deathbybandaid/tdarr_inform#5]
1. Prepend each line in the log with a timestamp so you can better correlate entries
2. Try and make some of the messages a bit more verbose, like the "No match found", "No matches found, Exiting". There's no way for me to know what file it was trying to match to in case there are issues.
3. I'd recommend an external config file for the script_settings so that script updates don't require re-entering config info.

**Comment by deathbybandaid** [comment]
1) the timestamps are available in the sonarr logs
2) I can make it list what files it doesn't find, some of the output from sonarr is lists of files, so this could be nice. Comming soon
3) I have definitely written much more "full" programs. I had the thought process of all the things that I could do with this, and I think for what this is, this is out of scope.

**Comment by deathbybandaid** [comment]
closed with #6

**Comment by deathbybandaid** [comment]
Woke up with a change of heart, the script is going to get an overhaul and be much more complicated than it needs to be, stay tuned
